
// for (let i = 1; i <= 100; i++) {
//   if (i % 2 === 0 && i % 3 === 0) {
//     console.log("FizzBuzz")
//   }
//   else if (i % 2 === 0) {
//     console.log("Fizz")
//   }
//   else if (i % 3 === 0) {
//     console.log("Buzz")
//   }
//   else (console.log(i))
// }
  
  
  
//   const numbers = [1, 9, 23, 95, 52, 100]
  
//   const sortedNumbers = numbers.sort((b,a)=>{
//     return a - b
//   })
  
//   let highestValue = sortedNumbers[0]
  
//   console.log(highestValue)



// const firstName = "Luke Sterling"


// const myName = firstName.split("")
 
//  console.log(myName)
//  console.log(myName[5])





//   const numbers = [0, 9, 35, 79, 100]
  
//   const sortedNumbers = numbers.sort((b,a)=>{
//       return a - b
//     })
  
//   const highestValue = sortedNumbers[0]
                  
//   console.log(highestValue)


// const name = "Sterling"

// const nameArrayafied = name.split("")

// console.log(nameArrayafied)







// const numbers = [1, 9, 38, 75, 100]

// const sortedNumbers = numbers.sort((b,a)=>{
//   return a - b
// });

// let highestValue = sortedNumbers[0];

// console.log(sortedNumbers);

// console.log(highestValue);




const numbers = [3,24,867,45,75,345,8,3,23,7]

const numbersSlice = numbers.slice(4,6)

const mappedNumbers = numbers.map((number)=>(<div></div>))

console.log(mappedNumbers)




// const numbers = [7, 14, 56, 7, 67]

// const uniqueNumbers = [...new Set(numbers)]

// const sortedNumbers = uniqueNumbers.sort((a,b)=>{
//   return a - b
// })

// const lowestNumbers = sortedNumbers.slice(0,3)

// console.log(lowestNumbers)


                  
// const numbers = [1, 100, 11, 87, 51]

// const sortedNumbers = numbers.sort((b,a)=>{
//   return a - b
// })

// const highestValue = sortedNumbers[0]

// console.log(highestValue)



// for (let i = 1; i <= 100; i++) {
//   if (i % 2 === 0 && i % 3 === 0) {
//     console.log("FizzBuzz")
//   } 
//   else if (i % 2 === 0) {
//     console.log("Fizz")
//   }
//   else if (i % 3 === 0) {
//     console.log("Buzz")
//   }
//   else (console.log(i))
// }


// for (let i = 1; i <= 100; i++) {
//   if (i % 2 === 0 && i % 3 === 0) {
//     console.log("FizzBuzz")
//   }
//   else if (i % 2 === 0) {
//     console.log("Fizz")
//   }
//   else if (i % 3 === 0) {
//     console.log("Buzz")
//   }
//   else console.log(i)
// }

// function fizzBuzz(n){



// for (let i = 1; i <= n; i++) {
//   if (i % 3 === 0 && i % 5 === 0){
//     console.log("FizzBuzz")
//   }
//   else if (i % 3 === 0) {
//     console.log("Fizz")
//   }
//   else if (i % 5 === 0) {
//     console.log("Buzz")
//   }
//   else console.log(i)
//   }
// }

// fizzBuzz(15)




// const letters = ["zebra", "comb", "monty", "apple", "quick", "word", "emphasize", "roach", "taffy", "you", "umbrella", "integer", "oak", "people", "asinine", "superb", "dingleberry", "fraternitity", "goober", "hoover", "jackel", "kingship", "lollygag", "x-ray", "colockwheel", "venarial disease", "bogus", "nuclear"]

// // const splitLetters = letters.split("")

// const orderedLetters = letters.sort()

// console.log(orderedLetters)









                  
                  
                  
  
